# AUTOGENERATED by apply-theme.sh -- DO NOT EDIT
#
# Rendered to ~/.config/btop/themes/hykr.theme. apply-theme.sh also points
# btop.conf's color_theme at it, editing only that one key so the rest of
# your btop.conf is left alone.
#
# Load meters ramp cool -> warm (green -> yellow -> red) rather than
# reusing one accent for every gradient the way upstream HV-dotfiles does:
# these bars encode magnitude, and a monochrome ramp throws that away.

# Main background. Empty would mean "terminal default"; this is explicit so
# btop matches the rest of the theme even under a transparent terminal.
theme[main_bg]="{{bg}}"

# Main text color
theme[main_fg]="{{fg}}"

# Title color for boxes
theme[title]="{{accent}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{accent}}"

# Background color of selected item in processes box
theme[selected_bg]="{{surface}}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{accent}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{fg_dim}}"

# Color of text appearing on top of graphs
theme[graph_text]="{{fg_dim}}"

# Background color of the percentage meters
theme[meter_bg]="{{bg_alt}}"

# Misc colors for processes box
theme[proc_misc]="{{red}}"

# Box outlines
theme[cpu_box]="{{surface2}}"
theme[mem_box]="{{surface2}}"
theme[net_box]="{{surface2}}"
theme[proc_box]="{{surface2}}"
theme[div_line]="{{surface2}}"

# Temperature graph
theme[temp_start]="{{green}}"
theme[temp_mid]="{{yellow}}"
theme[temp_end]="{{red}}"

# CPU graph
theme[cpu_start]="{{green}}"
theme[cpu_mid]="{{yellow}}"
theme[cpu_end]="{{red}}"

# Mem/Disk free meter -- high is good, so this ramps toward the accent
theme[free_start]="{{overlay}}"
theme[free_mid]="{{teal}}"
theme[free_end]="{{green}}"

# Mem/Disk cached meter
theme[cached_start]="{{overlay}}"
theme[cached_mid]="{{blue}}"
theme[cached_end]="{{accent}}"

# Mem/Disk available meter
theme[available_start]="{{overlay}}"
theme[available_mid]="{{teal}}"
theme[available_end]="{{green}}"

# Mem/Disk used meter -- high is bad, so this ramps toward red
theme[used_start]="{{green}}"
theme[used_mid]="{{yellow}}"
theme[used_end]="{{red}}"

# Download graph
theme[download_start]="{{overlay}}"
theme[download_mid]="{{teal}}"
theme[download_end]="{{accent}}"

# Upload graph
theme[upload_start]="{{overlay}}"
theme[upload_mid]="{{pink}}"
theme[upload_end]="{{red}}"

# Process box gradient for threads, mem and cpu usage
theme[process_start]="{{overlay}}"
theme[process_mid]="{{accent}}"
theme[process_end]="{{fg}}"

# Graph gradient colors, dark -> light
theme[gradient_color_0]="{{surface2}}"
theme[gradient_color_1]="{{overlay}}"
theme[gradient_color_2]="{{blue}}"
theme[gradient_color_3]="{{teal}}"
theme[gradient_color_4]="{{accent}}"
theme[gradient_color_5]="{{fg}}"
theme[gradient_color_6]="{{yellow}}"
theme[gradient_color_7]="{{red}}"
