# AUTOGENERATED by apply-theme.sh -- DO NOT EDIT
#
# Rendered whole, not patched: cava reads its defaults for everything it is
# not told about, so a colours-only config is a complete config. Upstream
# HV-dotfiles ships exactly this (a lone [color] section) for the same
# reason. Anything you add here by hand is lost on the next theme switch --
# put persistent cava settings in ~/.config/cava/config.d/ if your cava
# build supports it, or fork this template.

[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '{{overlay}}'
gradient_color_2 = '{{blue}}'
gradient_color_3 = '{{teal}}'
gradient_color_4 = '{{green}}'
gradient_color_5 = '{{accent}}'
gradient_color_6 = '{{yellow}}'
gradient_color_7 = '{{orange}}'
gradient_color_8 = '{{red}}'
