/* Per-theme color overrides, generated by apply-theme.sh, loaded
   automatically by every GTK3 app (mirage included) from
   ~/.config/gtk-3.0/gtk.css on top of the base theme set in
   gtk-3.0/settings.ini (gtk-theme-name=Materia-dark). GTK3 has no
   libadwaita named-color system like GTK4 does -- these are plain
   selector overrides against Materia-dark's own widget classes instead. */

window, .background {
  background-color: {{bg}};
  color: {{fg}};
}

headerbar, .titlebar {
  background-color: {{bg_alt}};
  color: {{fg}};
  border-color: {{surface}};
}

.view, treeview, textview text {
  background-color: {{bg_alt}};
  color: {{fg}};
}

button {
  background-color: {{surface}};
  color: {{fg}};
}

button:hover {
  background-color: {{surface2}};
}

button.suggested-action {
  background-color: {{accent}};
  color: {{bg}};
}

button.destructive-action {
  background-color: {{red}};
  color: {{fg}};
}

selection, *:selected {
  background-color: {{accent}};
  color: {{bg}};
}

tooltip {
  background-color: {{surface}};
  color: {{fg}};
}

scrollbar slider {
  background-color: {{surface2}};
}
