/* libadwaita named colors, generated by apply-theme.sh from the active
   theme-switcher theme. Loaded automatically by every GTK4/libadwaita app
   (hyprmod included) from ~/.config/gtk-4.0/gtk.css. */

@define-color accent_color {{accent}};
@define-color accent_bg_color {{accent}};
@define-color accent_fg_color {{bg}};

@define-color destructive_color {{red}};
@define-color destructive_bg_color {{red}};
@define-color destructive_fg_color {{fg}};

@define-color success_color {{green}};
@define-color success_bg_color {{green}};
@define-color success_fg_color {{bg}};

@define-color warning_color {{yellow}};
@define-color warning_bg_color {{yellow}};
@define-color warning_fg_color {{bg}};

@define-color error_color {{red}};
@define-color error_bg_color {{red}};
@define-color error_fg_color {{fg}};

@define-color window_bg_color {{bg}};
@define-color window_fg_color {{fg}};

@define-color view_bg_color {{bg_alt}};
@define-color view_fg_color {{fg}};

@define-color headerbar_bg_color {{bg_alt}};
@define-color headerbar_fg_color {{fg}};
@define-color headerbar_border_color {{surface}};
@define-color headerbar_backdrop_color {{bg}};
@define-color headerbar_shade_color {{shadow}};

@define-color card_bg_color {{surface}};
@define-color card_fg_color {{fg}};
@define-color card_shade_color {{shadow}};

@define-color dialog_bg_color {{bg_alt}};
@define-color dialog_fg_color {{fg}};

@define-color popover_bg_color {{surface}};
@define-color popover_fg_color {{fg}};

@define-color sidebar_bg_color {{bg_alt}};
@define-color sidebar_fg_color {{fg}};
@define-color sidebar_backdrop_color {{bg}};
@define-color sidebar_border_color {{surface}};

@define-color shade_color {{shadow}};
@define-color scrollbar_outline_color {{surface2}};
