; AUTOGENERATED by apply-theme.sh -- don't hand-edit, changes are
; overwritten on the next theme switch or wallpaper pick.

[HyKr]
accent             = {{accent}}
accent-active      = {{accent}}
accent-inactive    = {{surface2}}
banner             = {{accent}}
border-active      = {{accent}}
border-inactive    = {{surface2}}
header             = {{surface}}
highlight          = {{surface2}}
main               = {{bg}}
notification       = {{accent}}
notification-error = {{red}}
subtext            = {{fg_dim}}
text               = {{fg}}
