"$schema" = 'https://starship.rs/config-schema.json'

palette = "hykr"

add_newline = true
command_timeout = 1000

format = """
[](fg:mauve)[ $os ](bg:mauve fg:base)[](fg:mauve bg:surface)$directory$git_branch$git_status[](fg:surface)
$character"""

[palettes.hykr]
base    = "#11111b"
surface = "#1e1e2e"
text    = "#cdd6f4"
blue    = "#89b4fa"
green   = "#a6e3a1"
yellow  = "#f9e2af"
red     = "#f38ba8"
mauve   = "#cba6f7"

[os]
disabled = false
style = "bg:mauve fg:base"

[os.symbols]
Arch = " "
Ubuntu = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
Windows = "󰍲 "

[directory]
style = "bg:surface fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[git_branch]
symbol = " "
style = "bg:surface fg:green"
format = "[$symbol$branch ]($style)"

[git_status]
style = "bg:surface fg:yellow"
format = "([$all_status$ahead_behind ]($style))"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[package]
disabled = true

[cmd_duration]
disabled = true
