# AUTOGENERATED - DO NOT EDIT

general {
  gaps_in = {{gaps_in}}
  gaps_out = {{gaps_out}}
  border_size = {{border_size}}

  col.active_border = {{border_active}}
  col.inactive_border = {{border_inactive}}

  layout = {{layout}}
}

decoration {
  rounding = {{rounding}}

  shadow {
    enabled = {{shadow_enabled}}
    range = {{shadow_range}}
    render_power = {{shadow_power}}
    color = {{shadow_color}}
  }

  blur {
    enabled = {{blur_enabled}}
    size = {{blur_size}}
    passes = {{blur_passes}}
    vibrancy = {{blur_vibrancy}}
  }
}

# decoration:active_opacity/inactive_opacity silently no-ops on this
# Hyprland version (confirmed live: hyprctl getoption kept reporting
# set: false / 1.0 no matter what, and `hyprctl keyword` itself errors
# with "can't work with non-legacy parsers" here) -- global opacity has
# to go through the windowrule system instead, the same mechanism
# already used for dolphin's per-app opacity rule.
windowrule = match:class ^(.*)$, opacity {{active_opacity}} {{inactive_opacity}}

# Layer rules
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.2, match:namespace waybar

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0.2, match:namespace wofi

layerrule = blur on, match:class wlogout
layerrule = ignore_alpha 0.2, match:class wlogout

# Hyprshot selection fix
layerrule = blur off, match:namespace selection
