-- AUTOGENERATED - DO NOT EDIT

hl.config({
    general = {
        gaps_in = {{gaps_in}},
        gaps_out = {{gaps_out}},
        border_size = {{border_size}},

        col = {
            active_border = "{{border_active}}",
            inactive_border = "{{border_inactive}}",
        },

        layout = "{{layout}}",
    },

    decoration = {
        rounding = {{rounding}},

        shadow = {
            enabled = {{shadow_enabled}},
            range = {{shadow_range}},
            render_power = {{shadow_power}},
            color = "{{shadow_color}}",
        },

        blur = {
            enabled = {{blur_enabled}},
            size = {{blur_size}},
            passes = {{blur_passes}},
            vibrancy = {{blur_vibrancy}},
        },
    },
})

-- decoration.active_opacity/inactive_opacity silently no-op on this
-- Hyprland version (confirmed live: hyprctl getoption kept reporting
-- set: false / 1.0 no matter what) -- global opacity goes through the
-- window-rule system instead, the same mechanism used for dolphin's
-- per-app opacity rule below.
hl.window_rule({
    match = { class = "^(.*)$" },
    opacity = "{{active_opacity}} {{inactive_opacity}}",
})

-- Layer rules
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "wofi" }, blur = true })
hl.layer_rule({ match = { namespace = "wofi" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { class = "wlogout" }, blur = true })
hl.layer_rule({ match = { class = "wlogout" }, ignore_alpha = 0.2 })

-- Hyprshot selection fix
hl.layer_rule({ match = { namespace = "selection" }, blur = false })
