-- AUTOGENERATED - DO NOT EDIT

hl.config({
    general = {
        gaps_in = {{gaps_in}},
        gaps_out = {{gaps_out}},
        border_size = {{border_size}},

        -- Both of these are overwritten a few lines later in
        -- hypr/hyprland.lua by var_color4/var_backgroundCol out of
        -- colors-hyprland.lua -- that file is the one surface the
        -- wallpaper-matched border actually comes from (apply-theme.sh
        -- writes it from this theme's freshly generated accent, and
        -- apply_wallpaper.sh rewrites it from pywal's $color4 on a plain
        -- wallpaper pick). These stay here so the generated config is
        -- still complete on its own.
        col = {
            active_border = "{{border_active}}",
            inactive_border = "{{border_inactive}}",
        },

        layout = "{{layout}}",
    },

    decoration = {
        rounding = {{rounding}},

        shadow = {
            enabled = {{shadow_enabled}},
            range = {{shadow_range}},
            render_power = {{shadow_power}},
            color = "{{shadow_color}}",
        },

        blur = {
            enabled = {{blur_enabled}},
            size = {{blur_size}},
            passes = {{blur_passes}},
            vibrancy = {{blur_vibrancy}},
        },
    },
})

hl.window_rule({
    match = { class = "^(.*)$" },
    opacity = "{{active_opacity}} {{inactive_opacity}}",
})

-- Layer rules. Hyperspace runs its own Quickshell shell
-- (`quickshell -c hyperspace`) instead of waybar/swaync, so these target
-- that shell's layer-shell namespaces.
--
-- ignore_alpha = 0.2 matters more here than it does for a full-width bar:
-- the Hyperspace dock is ONE transparent layer surface with three opaque
-- islands drawn inside it, so without this threshold Hyprland would blur
-- the empty gaps between the islands too -- a smeared band across the top
-- of the wallpaper where there is supposed to be nothing at all. At 0.2,
-- only the islands (0.55 alpha) are blurred and the gaps are left alone.
hl.layer_rule({ match = { namespace = "hyperspace-dock" }, blur = true })
hl.layer_rule({ match = { namespace = "hyperspace-dock" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "hyperspace-popup" }, blur = true })
hl.layer_rule({ match = { namespace = "hyperspace-popup" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "wofi" }, blur = true })
hl.layer_rule({ match = { namespace = "wofi" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { class = "wlogout" }, blur = true })
hl.layer_rule({ match = { class = "wlogout" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "selection" }, blur = false })
