// Horizontal top dock bar -- moved from the original vertical "Dock
// Rail" mockup per request, thinned down, and given the same opacity
// Hyprland's own window_rule applies to focused windows (0.9) so it
// reads as part of the same translucent-window look rather than a
// solid, un-transparent strip.
//
// Layout, left to right: workspaces / (centered) clock / battery,
// volume, network, bluetooth, date, notifications.
//
// The four popup panels are NOT declared here anymore -- see shell.qml's
// header comment: nesting multiple PanelWindows as children of another
// PanelWindow was unreliable on real hardware (intermittent "X is not a
// type" errors, always one of the later-declared nested windows). They're
// now top-level siblings in shell.qml, coordinated through DockState.qml.
//
// Same multi-monitor-safe screen pattern as the other HyKr quickshell
// configs (wallpaper-picker, hykr): PanelWindow needs an explicit
// screen or it can silently fail to attach to any output at all.
//
// Every icon glyph below is written as a \u/\u{} JS escape rather than
// typed directly -- confirmed via byte inspection (od -c) that typing
// these Nerd Font codepoints directly into this file previously
// produced literally empty strings, particularly the ones above
// U+FFFF (volume, bluetooth). Codepoints reused from this repo's own
// waybar/swaync configs for visual consistency.
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import Quickshell.Wayland
import QtQuick
import QtQuick.Layouts
import "./services" as Services

PanelWindow {
    id: root

    required property var modelData
    readonly property var targetScreen: modelData

    readonly property int barHeight: 34

    screen: targetScreen
    color: "transparent"
    implicitHeight: barHeight
    exclusiveZone: barHeight

    anchors { top: true; left: true; right: true }

    WlrLayershell.layer: WlrLayer.Top
    WlrLayershell.namespace: "laptop-dock"

    readonly property var workspaceIds: [1, 2, 3, 4, 5]
    readonly property var monitorWorkspaces: Hyprland.workspaces
        ? Hyprland.workspaces.values.filter(w => w.monitor && w.monitor.name === root.targetScreen.name)
        : []
    readonly property int activeWorkspaceId: {
        const active = monitorWorkspaces.find(w => w.active);
        return active ? active.id : -1;
    }

    // Background only -- alpha lives in the color itself (not the
    // Rectangle's opacity property), because opacity cascades to
    // children in Qt Quick. It was set on this Rectangle while the
    // RowLayout/clock were declared INSIDE it, so every icon and text
    // label was also rendering at 90% opacity instead of just the
    // background showing wallpaper through -- reported as "no
    // transparency" since a slightly-faded bar reads the same as an
    // opaque one at a glance. Content now lives as siblings below,
    // full opacity, on top of this.
    Rectangle {
        anchors.fill: parent
        color: Qt.rgba(0.039, 0.078, 0.071, 0.55) // #0a1412 at 55% alpha
        border.width: 1
        border.color: Qt.rgba(1, 1, 1, 0.06)
    }

    Item {
        anchors.fill: parent

        RowLayout {
            anchors.fill: parent
            anchors.leftMargin: 14
            anchors.rightMargin: 14
            spacing: 18

            // ---- left: workspaces ----
            Row {
                Layout.alignment: Qt.AlignVCenter
                spacing: 7

                Repeater {
                    model: root.workspaceIds
                    delegate: Rectangle {
                        readonly property bool isActive: modelData === root.activeWorkspaceId
                        width: isActive ? 18 : 6
                        height: isActive ? 8 : 6
                        radius: isActive ? 4 : 3
                        anchors.verticalCenter: parent.verticalCenter
                        // Colors.accent tracks the wallpaper -- regenerated by
                        // apply-theme.sh on a theme switch and by
                        // apply_wallpaper.sh on a wallpaper pick, same as kitty
                        // and starship. See Colors.qml. The inactive pips stay
                        // a neutral white alpha: they read as "unlit", and
                        // tinting them too would leave nothing for the active
                        // one to contrast against.
                        color: isActive ? Colors.accent : Qt.rgba(1, 1, 1, 0.22)

                        Behavior on width { NumberAnimation { duration: 120 } }

                        TapHandler {
                            onTapped: Hyprland.dispatch("workspace " + modelData)
                        }
                    }
                }
            }

            Item { Layout.fillWidth: true }

            // ---- right: battery, volume, network, bluetooth, date, notifications ----
            Row {
                Layout.alignment: Qt.AlignVCenter
                spacing: 16

                // Battery sits at the head of this group -- i.e. immediately
                // left of the Wi-Fi and bluetooth icons -- and disappears
                // entirely on a machine with no battery, since this same
                // shell config also runs on the desktop's three monitors.
                // A Row skips invisible children, so nothing else shifts.
                //
                // Hovering it slides out the exact percentage. Inline rather
                // than a floating tooltip window on purpose: this bar's layer
                // surface is only barHeight (34px) tall, so anything drawn
                // below the icon would be clipped off, and an extra
                // PanelWindow is the very pattern shell.qml's header warns
                // about.
                Item {
                    id: batteryItem
                    width: batteryRow.implicitWidth
                    height: 20
                    visible: Services.BatteryService.available

                    HoverHandler { id: batteryHover }

                    Row {
                        id: batteryRow
                        spacing: batteryHover.hovered ? 5 : 0

                        Behavior on spacing { NumberAnimation { duration: 120 } }

                        // Deliberately BEFORE the glyph. The whole group is
                        // pushed right by the RowLayout's filler, so it grows
                        // leftwards into empty bar: with the label first, the
                        // battery glyph itself never moves as the label
                        // appears. After the glyph it would slide the icon out
                        // from under the pointer, dropping the hover and
                        // flickering the label on and off. Either way nothing
                        // to the right (volume, network, bluetooth, date,
                        // bell) shifts by a pixel, so the popup panels'
                        // rightOffset values stay correct.
                        Text {
                            id: batteryPercent
                            anchors.verticalCenter: parent.verticalCenter
                            text: Services.BatteryService.percent + "%"
                            font.pixelSize: 11
                            font.family: "monospace"
                            color: Services.BatteryService.low ? "#c8102e" : "#c8d4d1"
                            // Animating width rather than toggling visible
                            // slides the label out from behind the icon, and
                            // clip keeps the digits inside whatever width it
                            // currently has. implicitWidth is pure text
                            // metrics, so this can't feed back into itself.
                            width: batteryHover.hovered ? implicitWidth : 0
                            clip: true
                            opacity: batteryHover.hovered ? 1 : 0

                            Behavior on width { NumberAnimation { duration: 120 } }
                            Behavior on opacity { NumberAnimation { duration: 120 } }
                        }

                        Item {
                            width: 20
                            height: 20

                            Text {
                                anchors.centerIn: parent
                                // nf-md-battery_* and nf-md-battery_charging_*.
                                // Material Design's battery ramps are not
                                // evenly spaced -- the discharging set has
                                // every tenth, the charging set skips
                                // 10/50/70 -- so each threshold below maps to
                                // the nearest glyph that actually exists
                                // rather than a computed decile.
                                text: {
                                    const p = Services.BatteryService.percent;
                                    if (Services.BatteryService.charging) {
                                        if (p >= 95) return "\u{F0085}"; // charging_100
                                        if (p >= 90) return "\u{F008B}"; // charging_90
                                        if (p >= 80) return "\u{F008A}"; // charging_80
                                        if (p >= 60) return "\u{F0089}"; // charging_60
                                        if (p >= 40) return "\u{F0088}"; // charging_40
                                        if (p >= 30) return "\u{F0087}"; // charging_30
                                        if (p >= 20) return "\u{F0086}"; // charging_20
                                        return "\u{F0084}"; // charging (generic)
                                    }
                                    if (p >= 95) return "\u{F0079}"; // battery (full)
                                    if (p >= 90) return "\u{F0082}"; // battery_90
                                    if (p >= 80) return "\u{F0081}"; // battery_80
                                    if (p >= 70) return "\u{F0080}"; // battery_70
                                    if (p >= 60) return "\u{F007F}"; // battery_60
                                    if (p >= 50) return "\u{F007E}"; // battery_50
                                    if (p >= 40) return "\u{F007D}"; // battery_40
                                    if (p >= 30) return "\u{F007C}"; // battery_30
                                    if (p >= 20) return "\u{F007B}"; // battery_20
                                    if (p >= 10) return "\u{F007A}"; // battery_10
                                    return "\u{F008E}"; // battery_outline (empty)
                                }
                                font.family: "JetBrainsMono Nerd Font"
                                font.pixelSize: 15
                                // Same accent the other icons use for "needs
                                // your attention", here meaning on battery and
                                // under 15%.
                                color: Services.BatteryService.low ? "#c8102e" : "#9fb3ae"
                            }
                        }
                    }
                }

                Item {
                    width: 20; height: 20
                    Text {
                        anchors.centerIn: parent
                        // nf-md-volume_high / nf-md-volume_mute
                        text: Services.AudioService.muted ? "\u{F075F}" : "\u{F057E}"
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        color: DockState.isActive(root.targetScreen, "volume") ? "#c8102e" : "#9fb3ae"
                    }
                    TapHandler { onTapped: DockState.toggle(root.targetScreen, "volume") }
                }

                Item {
                    width: 20; height: 20
                    Text {
                        anchors.centerIn: parent
                        // nf-fa-wifi / nf-custom-ethernet / nf-md-network_off
                        text: Services.NetworkService.connectionType === "wifi" ? ""
                            : Services.NetworkService.connectionType === "ethernet" ? "" : ""
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        color: DockState.isActive(root.targetScreen, "network") ? "#c8102e" : "#9fb3ae"
                    }
                    TapHandler {
                        acceptedButtons: Qt.LeftButton
                        onTapped: DockState.toggle(root.targetScreen, "network")
                    }
                    TapHandler {
                        acceptedButtons: Qt.RightButton
                        onTapped: Services.NetworkService.openNetworkManager()
                    }
                }

                Item {
                    width: 20; height: 20
                    Text {
                        anchors.centerIn: parent
                        // nf-md-bluetooth
                        text: "\u{F00AF}"
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        color: DockState.isActive(root.targetScreen, "bluetooth") ? "#c8102e"
                            : (Services.BluetoothService.powered ? "#9fb3ae" : "#5c6d6a")
                    }
                    TapHandler { onTapped: DockState.toggle(root.targetScreen, "bluetooth") }
                }

                Text {
                    anchors.verticalCenter: parent.verticalCenter
                    text: Qt.formatDateTime(clock.now, "ddd d")
                    color: "#c8d4d1"
                    font.pixelSize: 12
                    font.family: "monospace"
                }

                Item {
                    width: 20; height: 20
                    anchors.verticalCenter: parent.verticalCenter

                    Text {
                        anchors.centerIn: parent
                        // nf-md-bell
                        text: ""
                        font.family: "JetBrainsMono Nerd Font"
                        font.pixelSize: 15
                        color: DockState.isActive(root.targetScreen, "notifications") ? "#c8102e" : "#9fb3ae"
                    }
                    Rectangle {
                        visible: Services.NotificationService.unreadCount > 0
                        width: 6; height: 6; radius: 3
                        color: "#f87171"
                        anchors.top: parent.top
                        anchors.right: parent.right
                    }
                    TapHandler { onTapped: DockState.toggle(root.targetScreen, "notifications") }
                }
            }
        }

        // ---- center: clock ----
        // A separate item anchored to the bar's true center, rather than
        // a RowLayout child -- the left (workspaces) and right (controls)
        // groups are different widths, so centering this within the
        // RowLayout's flexible space wouldn't land it in the middle of
        // the whole bar.
        Text {
            anchors.centerIn: parent
            text: Qt.formatDateTime(clock.now, "hh:mm")
            color: "#eaf0ee"
            font.pixelSize: 12
            font.family: "monospace"
        }
    }

    // The only consumers of clock.now render "hh:mm" and "ddd d" -- neither
    // changes more than once a minute, so a 1000 ms repeat was waking the
    // shell (and repainting) 60x more often than the display could possibly
    // differ. That is exactly the sort of idle wakeup that costs battery on
    // the machine this theme exists for. Instead: fire once, at the next
    // minute boundary, then re-arm for the following one. `repeat: false`
    // plus a recomputed interval keeps it aligned to :00 seconds rather
    // than drifting by however long the shell took to start.
    Timer {
        id: clock
        property date now: new Date()

        function msToNextMinute() {
            const d = new Date();
            return 60000 - (d.getSeconds() * 1000 + d.getMilliseconds());
        }

        interval: msToNextMinute()
        running: true
        repeat: false
        onTriggered: {
            now = new Date();
            interval = msToNextMinute();
            restart();
        }
    }
}
