#!/usr/bin/env bash
# Freeze the monitor layout this machine is running RIGHT NOW into
# ~/.config/hypr/monitors.lua, which hyprland.lua pcall-requires.
#
# Monitor layout is the one part of this repo that cannot be shared: output
# names like HDMI-A-1 and eDP-1 are the first HDMI output and the internal
# panel on nearly any machine, so a layout committed to hyprland.lua lands on
# someone else's hardware and rotates their display 90 degrees on first login.
# monitors.lua is gitignored for that reason -- which leaves the question of
# how you produce one, and hand-editing a commented example is how you end up
# with a scale you did not ask for.
#
# So: arrange the displays however you like with hyprctl (or nwg-displays, or
# hyprmod), confirm it looks right, then run this once to make it permanent.
#
#   snapshot_monitors.sh                 write ~/.config/hypr/monitors.lua
#   snapshot_monitors.sh --print         print it instead, change nothing
#   snapshot_monitors.sh --preferred     write mode = "preferred" rather than
#                                        pinning the exact current mode
#   snapshot_monitors.sh --output FILE   write somewhere else
#
# Pins scale and transform as well as mode and position, deliberately. Neither
# survives a config reload on its own: a rotation or a scale set live with
# `hyprctl keyword` is never written back anywhere, so without this the next
# `hyprctl reload` silently drops it and falls through to hyprland.lua's
# `output = ""` catch-all -- which is `scale = "auto"`, i.e. a DPI-derived
# (often fractional) scale you did not choose.

scrDir="$(dirname "$(realpath "$0")")"
source "${scrDir}/global_fn.sh" || {
    echo "Error: unable to source ${scrDir}/global_fn.sh"
    ls -la "${scrDir}/global_fn.sh" 2>&1
    exit 1
}

OUT="${HOME}/.config/hypr/monitors.lua"
PRINT_ONLY=false
USE_PREFERRED=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --print|-p)     PRINT_ONLY=true; shift ;;
        --preferred)    USE_PREFERRED=true; shift ;;
        --output|-o)    OUT="${2:?--output needs a path}"; shift 2 ;;
        -h|--help)      sed -n '2,27p' "$(realpath "$0")"; exit 0 ;;
        *)              print_log "Unknown argument: $1"; exit 1 ;;
    esac
done

for tool in hyprctl jq; do
    command -v "$tool" &>/dev/null || {
        print_log "${tool} not found -- it's in pkg_core.lst, install it first."
        exit 1
    }
done

# Reading the layout needs a compositor to read it from. Without this the
# error is an opaque jq parse failure on hyprctl's "no instance" message.
if [[ -z "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
    print_log "No running Hyprland (HYPRLAND_INSTANCE_SIGNATURE unset)."
    print_log "Run this from inside your Hyprland session -- it snapshots the live layout."
    exit 1
fi

monitors_json="$(hyprctl monitors -j 2>/dev/null)" || {
    print_log "hyprctl monitors failed."
    exit 1
}

# `disabled` monitors are ones Hyprland knows about but is not driving. Writing
# a rule for one would re-enable it on the next reload, which is not what
# "snapshot what I am looking at" means.
count="$(jq '[.[] | select(.disabled != true)] | length' <<<"${monitors_json}")"
if [[ "${count}" -eq 0 ]]; then
    print_log "hyprctl reported no enabled monitors -- nothing to snapshot."
    exit 1
fi

# refreshRate comes back as a float with more precision than Hyprland's own
# mode strings use (239.96400); round to 2dp and strip trailing zeros so
# 144.00000 -> 144 and 239.96400 -> 239.96, matching how these are written by
# hand. transform is omitted when 0 (the default) to keep the file readable.
rendered="$(jq -r --argjson preferred "$($USE_PREFERRED && echo true || echo false)" '
    def trim: tostring | sub("0+$"; "") | sub("\\.$"; "");
    [ .[] | select(.disabled != true) ] | .[] |
    "hl.monitor({ output = \"\(.name)\""
    + ", mode = " + (if $preferred then "\"preferred\""
                     else "\"\(.width)x\(.height)@\((.refreshRate * 100 | round / 100) | trim)\"" end)
    + ", position = \"\(.x)x\(.y)\""
    + ", scale = \((.scale * 100 | round / 100) | trim)"
    + (if (.transform // 0) != 0 then ", transform = \(.transform)" else "" end)
    + " })"
    + (if (.transform // 0) != 0 then " -- \((.transform % 4) * 90) deg" else "" end)
' <<<"${monitors_json}")"

header="$(cat <<EOF
-- Per-machine monitor layout for $(hostnamectl --static 2>/dev/null || hostname 2>/dev/null || echo "this machine").
-- Generated by Scripts/snapshot_monitors.sh on $(date '+%Y-%m-%d %H:%M') from the
-- live layout; re-run it after rearranging displays.
--
-- Gitignored on purpose: output names are not distinctive (HDMI-A-1 is the
-- first HDMI output and eDP-1 the internal panel on nearly any machine), so a
-- layout committed to hyprland.lua would land on someone else's hardware.
-- hyprland.lua pcall-requires this file and falls back to its
-- \`output = ""\` catch-all when it is absent.
--
-- scale and transform are pinned because neither survives a reload on its own.
-- transform: 0 = normal, 1 = 90 deg, 2 = 180 deg, 3 = 270 deg.
EOF
)"

if $PRINT_ONLY; then
    printf '%s\n\n%s\n' "${header}" "${rendered}"
    exit 0
fi

mkdir -p "$(dirname "${OUT}")"

# Never silently replace a layout someone tuned by hand.
if [[ -e "${OUT}" ]]; then
    backup="${OUT}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${OUT}" "${backup}"
    print_log "Backed up existing ${OUT} -> ${backup}"
fi

printf '%s\n\n%s\n' "${header}" "${rendered}" > "${OUT}"
print_log "Wrote ${count} monitor(s) to ${OUT}:"
printf '%s\n' "${rendered}" | sed 's/^/    /'
print_log ""
print_log "Apply it with:  hyprctl reload"
