-- AUTOGENERATED - DO NOT EDIT

-- Blackturq's own look_and_feel.lua used an 8-stop gradient for
-- col.active_border. That does not survive the trip into this template:
-- apply-theme.sh renders {{border_active}} as a SINGLE rgba() value
-- because Hyprland's Lua config validates col.active_border as one colour,
-- not as hyprlang's "<colour> <colour> <angle>deg" string (see the note
-- above the border_active assignment in apply-theme.sh). So the flat
-- turquoise below is deliberate, not a dropped feature -- a gradient here
-- would make both consumers reject the value and fall back to unthemed
-- borders.
hl.config({
    general = {
        gaps_in = {{gaps_in}},
        gaps_out = {{gaps_out}},
        border_size = {{border_size}},

        col = {
            active_border = "{{border_active}}",
            inactive_border = "{{border_inactive}}",
        },

        layout = "{{layout}}",
    },

    decoration = {
        rounding = {{rounding}},

        -- rounding_power is NOT set here even though Blackturq upstream
        -- uses 3: theme.json has no field for it, so hardcoding it would
        -- make this the one theme whose corner profile can't be tuned
        -- from its theme.json like every other value in this block.

        shadow = {
            enabled = {{shadow_enabled}},
            range = {{shadow_range}},
            render_power = {{shadow_power}},
            color = "{{shadow_color}}",
        },

        blur = {
            enabled = {{blur_enabled}},
            size = {{blur_size}},
            passes = {{blur_passes}},
            vibrancy = {{blur_vibrancy}},
        },
    },
})

-- decoration.active_opacity/inactive_opacity silently no-op on this
-- Hyprland version -- global opacity goes through the window-rule system
-- instead. Same mechanism, same reason, as every other theme here.
hl.window_rule({
    match = { class = "^(.*)$" },
    opacity = "{{active_opacity}} {{inactive_opacity}}",
})

-- Layer rules. These name HyKr's own surfaces (waybar/wofi/wlogout), not
-- Blackturq upstream's (which blurs mako and walker instead) -- those two
-- processes are not part of this stack. See this theme's README.md.
hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "wofi" }, blur = true })
hl.layer_rule({ match = { namespace = "wofi" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "swaync-notification-window" }, blur = true })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, blur = true })

hl.layer_rule({ match = { class = "wlogout" }, blur = true })
hl.layer_rule({ match = { class = "wlogout" }, ignore_alpha = 0.2 })

-- Hyprshot selection fix
hl.layer_rule({ match = { namespace = "selection" }, blur = false })
