-- Monitors: pinned explicitly (name/resolution/refresh/position/transform)
-- so this survives reboots and config reloads instead of Hyprland
-- re-guessing a layout each time -- transform is NOT one of the things
-- that survives a reload on its own: a rotation set live (hyprmod, or a
-- one-off `hyprctl keyword monitor ...`) never gets written back here, so
-- without pinning it explicitly every `hyprctl reload` silently reset both
-- of these back to unrotated.
-- From `hyprctl monitors`:
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@144", position = "0x370", scale = 1, transform = 1 }) -- 90 deg
hl.monitor({ output = "DP-2", mode = "2560x1440@240", position = "1080x0", scale = 1, transform = 2 }) -- 180 deg
hl.monitor({ output = "DP-3", mode = "1920x1080@239.96", position = "1080x1440", scale = 1 })
-- Fallback for any monitor not listed above
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- Pywal colors for window borders. wal -i renders
-- Configs/configs/wal/templates/colors-hyprland.lua into ~/.cache/wal/,
-- and apply_wallpaper.sh/wallpaper.sh copy it into ~/.config/hypr/ right
-- after, same as they already do for kitty's current-theme.conf --
-- Lua's require() only resolves modules under the config root, so a file
-- that has to be reachable this way can't stay in ~/.cache.
require("colors-hyprland")

-- theme-switcher's gaps/border_size/rounding/opacity/shadow/blur/layerrules,
-- regenerated by apply-theme.sh from each theme's theme.json.
require("generated-theme")

-- Route Qt apps (dolphin, kate) through qt6ct-kde (pkg_core.lst) so they
-- pick up the color scheme apply-theme.sh generates at
-- ~/.config/qt6ct/colors/hykr.conf. Plain qt6ct doesn't style KDE
-- Frameworks apps like dolphin correctly -- needs the qt6ct-kde fork,
-- which keeps the same env value and config path/format.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Pywal border colors always win over the active theme's border colors,
-- same as every other "last write wins" surface in this repo (kitty,
-- starship, spicetify) -- var_color4/var_backgroundCol come from the
-- require("colors-hyprland") above.
hl.config({
    general = {
        col = {
            active_border = var_color4,
            inactive_border = var_backgroundCol,
        },
    },
})

-- --------------------------------------------------- // Trackpad gestures & Mission Control
-- hyprexpo was retired from the official hyprwm/hyprland-plugins repo
-- (github.com/hyprwm/hyprland-plugins/pull/663) -- sandwichfarm/hyprexpo is
-- the actively maintained continuation this repo tracks instead. Both it
-- and hyprgrass are hyprpm-managed plugins (installed by
-- Scripts/extra/setup_hypr_gestures.sh), not pacman packages, so neither
-- shows up in pkg_core.lst/pkg_extra.lst.
local function has_trackpad()
    local f = io.open("/proc/bus/input/devices", "r")
    if not f then return false end
    local contents = f:read("*a")
    f:close()
    return contents:lower():find("touchpad") ~= nil
end

-- `hyprpm enable <name>` can succeed while the actual build fails (seen in
-- practice: hyprgrass's -backlight/-pulse sub-plugins failing to compile
-- while hyprgrass itself, or hyprexpo, build fine) -- hl.config() for a
-- plugin category Hyprland doesn't recognize because it never actually
-- loaded is a hard parse-time error that takes down the WHOLE config file,
-- every keybind included. Check hl.get_loaded_plugins() before touching
-- any plugin.* config/function so one failed build can't do that again.
local function is_plugin_loaded(name)
    for _, plugin in ipairs(hl.get_loaded_plugins()) do
        if plugin.name == name then return true end
    end
    return false
end

-- hyprexpo works fine driven by mouse/keyboard alone, so its config and
-- O keybind (below, with var_mainMod) always load -- only the touchpad
-- swipe *trigger* for it is hardware-gated below.
if is_plugin_loaded("hyprexpo") then
    hl.config({
        plugin = {
            hyprexpo = {
                columns = 3,
                gaps_in = 5,
                gaps_out = 10,
                workspace_method = "center current",
                gesture_distance = 200,
                cancel_key = "escape",
                show_cursor = 1,
                keynav_enable = 1,
            },
        },
    })
end

-- Desktop has no touchpad, laptop does -- same repo, same file, no
-- per-machine config branch needed.
if has_trackpad() then
    -- Native 3-finger horizontal swipe between workspaces -- built into
    -- Hyprland itself, no plugin required
    hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

    if is_plugin_loaded("hyprexpo") then
        -- 4-finger swipe up opens the hyprexpo overview -- hyprexpo handles
        -- this gesture itself, no need to route it through hyprgrass
        hl.plugin.hyprexpo.gesture({ fingers = 4, direction = "up", action = "expo" })
    end

    if is_plugin_loaded("hyprgrass") then
        -- hyprgrass covers the gestures neither native `hl.gesture` nor
        -- hyprexpo's own gesture hook do
        hl.config({
            plugin = {
                hyprgrass = {
                    sensitivity = 1.0,
                    long_press_delay = 400,
                    resize_on_border_long_press = true,
                    edge_margin = 10,
                },
            },
            gestures = {
                workspace_swipe_touch = true,
                workspace_swipe_cancel_ratio = 0.15,
            },
        })

        hl.plugin.hyprgrass.bind({
            pattern = { kind = "tap", fingers = 3 },
            action = hl.dsp.window.float(),
        })
        hl.plugin.hyprgrass.bind({
            pattern = { kind = "pinch", fingers = 3, direction = "pinchin" },
            action = hl.dsp.window.close(),
        })
    end
end

-- Autostart
hl.on("hyprland.start", function()
    -- Secret storage (VS Code, browsers, etc. need this via libsecret --
    -- Hyprland has no keyring daemon of its own, unlike GNOME/KDE sessions)
    hl.exec_cmd("gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
    -- Polkit agent -- Hyprland has no polkit agent of its own either, so
    -- privilege-escalation prompts (mounting a drive from Dolphin, some
    -- NetworkManager/Bluetooth actions) silently fail or hang without one.
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wal -R")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("mkdir -p ~/Pictures/Screenshots")
end)

local var_terminal = "kitty"
local var_mainMod = "SUPER"
local var_menu = "wofi --show drun -n"
local var_fileManager = "dolphin"
local var_editor = "kate"
local var_browser = "brave"

-- Dropdown terminal on its own special workspace
hl.on("hyprland.start", function()
    hl.exec_cmd("[workspace special:dropterm silent] " .. var_terminal .. " --class dropterm")
end)
hl.window_rule({ match = { class = "^(dropterm)$" }, float = true })
hl.window_rule({ match = { class = "^(dropterm)$" }, size = "80% 60%" })

-- Dolphin: match the rest of the theming at 75% opacity
hl.window_rule({ match = { class = "^(org\\.kde\\.dolphin)$" }, opacity = "0.75 0.75" })

-- --------------------------------------------------- // Terminal
hl.bind(var_mainMod .. " + RETURN", hl.dsp.exec_cmd(var_terminal))
hl.bind(var_mainMod .. " + ALT + T", hl.dsp.workspace.toggle_special("dropterm"))

-- --------------------------------------------------- // Close, force-kill, exit
hl.bind(var_mainMod .. " + Q", hl.dsp.window.close())
hl.bind(var_mainMod .. " + ALT + F4", hl.dsp.exec_cmd("kill -9 $(hyprctl activewindow -j | jq -r .pid)"))
hl.bind(var_mainMod .. " + DELETE", hl.dsp.exit())
hl.bind(var_mainMod .. " + ESCAPE", hl.dsp.exec_cmd("wlogout"))
hl.bind(var_mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- --------------------------------------------------- // Toggle
hl.bind(var_mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(var_mainMod .. " + G", hl.dsp.group.toggle())
hl.bind(var_mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(var_mainMod .. " + M", hl.dsp.exec_cmd("pkill -x -f 'quickshell -c hykr' || quickshell -c hykr"))
hl.bind(var_mainMod .. " + CTRL + B", hl.dsp.exec_cmd("pkill waybar || waybar"))
hl.bind(var_mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(var_mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("pkill hyprsunset || hyprsunset"))
hl.bind(var_mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("pkill hypridle || hypridle"))
hl.bind(var_mainMod .. " + S", hl.dsp.exec_cmd("~/.config/hypr/quick_settings.sh"))
hl.bind(var_mainMod .. " + O", function()
    if is_plugin_loaded("hyprexpo") then hl.plugin.hyprexpo.expo("toggle") end
end)

-- --------------------------------------------------- // Launchers and apps
hl.bind(var_mainMod .. " + TAB", hl.dsp.exec_cmd(var_menu))
hl.bind(var_mainMod .. " + E", hl.dsp.exec_cmd(var_fileManager))
hl.bind(var_mainMod .. " + C", hl.dsp.exec_cmd(var_editor))
hl.bind(var_mainMod .. " + B", hl.dsp.exec_cmd(var_browser))
hl.bind(var_mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

-- --------------------------------------------------- // Workspace and theming
hl.bind(var_mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(var_mainMod .. " + CTRL + left", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(var_mainMod .. " + CTRL + down", hl.dsp.focus({ workspace = "empty" }))
hl.bind(var_mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill -9 -x -f 'quickshell -c wallpaper-picker'; ~/.config/quickshell/wallpaper-picker/launch.sh"))
hl.bind(var_mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("~/.config/theme-switcher/theme-picker.sh"))

-- --------------------------------------------------- // Alt
hl.bind("ALT + P", hl.dsp.window.pseudo())
hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }))

-- --------------------------------------------------- // Window movement
hl.bind(var_mainMod .. " + CTRL + H", hl.dsp.group.prev())
hl.bind(var_mainMod .. " + CTRL + L", hl.dsp.group.next())
hl.bind(var_mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(var_mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(var_mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(var_mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(var_mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }))
hl.bind(var_mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }))
hl.bind(var_mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }))
hl.bind(var_mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }))
hl.bind(var_mainMod .. " + CTRL + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(var_mainMod .. " + CTRL + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(var_mainMod .. " + CTRL + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(var_mainMod .. " + CTRL + SHIFT + down", hl.dsp.window.move({ direction = "down" }))
hl.bind(var_mainMod .. " + SHIFT + comma", hl.dsp.window.move({ monitor = "-1" }))
hl.bind(var_mainMod .. " + SHIFT + period", hl.dsp.window.move({ monitor = "+1" }))

-- Hold-to-move / hold-to-resize (arrows; Escape to exit)
hl.bind(var_mainMod .. " + Z", hl.dsp.submap("move"))
hl.define_submap("move", function()
    hl.bind("right", hl.dsp.window.move({ x = 30, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.move({ x = -30, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.move({ x = 0, y = -30, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.move({ x = 0, y = 30, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)
hl.bind(var_mainMod .. " + X", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

for i = 1, 10 do
    local key = i % 10
    hl.bind(var_mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(var_mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
    hl.bind(var_mainMod .. " + ALT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
end

-- Mission Control keyboard navigation while the hyprexpo overview is open
-- (hyprexpo enters this submap itself via plugin:hyprexpo:keynav_enable)
hl.define_submap("hyprexpo", function()
    hl.bind("h", function() hl.plugin.hyprexpo.kb_focus("left") end)
    hl.bind("l", function() hl.plugin.hyprexpo.kb_focus("right") end)
    hl.bind("k", function() hl.plugin.hyprexpo.kb_focus("up") end)
    hl.bind("j", function() hl.plugin.hyprexpo.kb_focus("down") end)
    hl.bind("return", function() hl.plugin.hyprexpo.kb_confirm() end)
    hl.bind("escape", function() hl.plugin.hyprexpo.expo("cancel") end)
end)

-- --------------------------------------------------- // Screenshot
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(var_mainMod .. " + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind(var_mainMod .. " + ALT + P", hl.dsp.exec_cmd("grim -o \"$(hyprctl monitors -j | jq -r '.[] | select(.focused==true) | .name')\" - | wl-copy"))
hl.bind(var_mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png"))

-- --------------------------------------------------- // Other (hardware, media, no modifier)
hl.bind("SHIFT + F11", hl.dsp.window.fullscreen())
hl.bind("F10", hl.dsp.exec_cmd("pamixer -t"), { locked = true })
hl.bind("F11", hl.dsp.exec_cmd("pamixer -d 5"), { locked = true, repeating = true })
hl.bind("F12", hl.dsp.exec_cmd("pamixer -i 5"), { locked = true, repeating = true })

-- --------------------------------------------------- // Mouse
hl.bind(var_mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(var_mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
