-- AUTOGENERATED - DO NOT EDIT

hl.config({
    general = {
        gaps_in = {{gaps_in}},
        gaps_out = {{gaps_out}},
        border_size = {{border_size}},

        col = {
            active_border = "{{border_active}}",
            inactive_border = "{{border_inactive}}",
        },

        layout = "{{layout}}",
    },

    decoration = {
        rounding = {{rounding}},

        shadow = {
            enabled = {{shadow_enabled}},
            range = {{shadow_range}},
            render_power = {{shadow_power}},
            color = "{{shadow_color}}",
        },

        blur = {
            enabled = {{blur_enabled}},
            size = {{blur_size}},
            passes = {{blur_passes}},
            vibrancy = {{blur_vibrancy}},
        },
    },
})

hl.window_rule({
    match = { class = "^(.*)$" },
    opacity = "{{active_opacity}} {{inactive_opacity}}",
})

-- Layer rules -- laptop theme runs the Quickshell dock + native
-- notification daemon (quickshell -c laptop) instead of waybar/swaync,
-- so these target that shell's layer-shell namespaces instead.
hl.layer_rule({ match = { namespace = "laptop-dock" }, blur = true })
hl.layer_rule({ match = { namespace = "laptop-dock" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "laptop-popup" }, blur = true })
hl.layer_rule({ match = { namespace = "laptop-popup" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "wofi" }, blur = true })
hl.layer_rule({ match = { namespace = "wofi" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { class = "wlogout" }, blur = true })
hl.layer_rule({ match = { class = "wlogout" }, ignore_alpha = 0.2 })

hl.layer_rule({ match = { namespace = "selection" }, blur = false })
